development:
  adapter: mysql2
  database: donely_dev
  username: root
  password:
  host: localhost
test:
  adapter: mysql2
  database: donely_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql2
  database: donely_prod
  username: root
  password:
  host: localhost
